---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: publish-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    repo: rancher/kube-api-auth
    tag: "${DRONE_TAG}"
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
